290 tests v2
0xSpaceShard/starknet-hardhat-plugin pull request #331
Opened 2023-03-05 11:52 UTC by shramee

## Usage related changes

Resolves #190

## Development related changes

- Tests can be run in a docker container
- Individual tests can be run with `npm run test-general-tests -- account-test`

## Checklist:

-   [x] Formatted the code
-   [x] No linter errors + tried to avoid introducing linter warnings
-   [x] Performed a self-review of the code
-   [x] Rebased to the last commit of the target branch (or merged it into my branch)
-   [x] Documented the changes
-   [ ] Updated the `test` directory (with a test case consisting of `network.json`, `hardhat.config.ts`, `check.ts`)
-   [x] Linked issues which this PR resolves
-   [ ] Created a PR to the `plugin` branch of [`starknet-hardhat-example`](https://github.com/Shard-Labs/starknet-hardhat-example):
    -   < EXAMPLE_REPO_PR_URL > 
    -   [ ] Modified `test.sh` to use my example repo branch
    -   [ ] Restored `test.sh` to to use the original branch (after the example repo PR has been merged)
-   [ ] All tests are passing (for external contributors who don't have access to the CI/CD pipeline)

2023-03-06 11:25 UTC, shramee commented
@FabijanC Here's the new PR for #296.

2023-03-09 15:16 UTC, FabijanC requested changes
There are failing tests, perhaps `/restart` is being invoked on a wrong network? I suggest you check the circleci logs.

Also, can you update the list of failing tests (or delete it?) in the PR description?

All in all, I am not very prone to accepting this PR as it currently is. I still don't fully understand what's going on and would have to invest more time in reviewing it. I cannot accept it on superficial understanding.

But more than that, I don't like that, if I understood correctly, what this PR is basically introducing is modifying the plugin to do:
```js
if  (testing) { do_this(); } else { do_that(); }
```

I am ok with modifying the testing code (the plugin tests), but not the code being tested (the plugin source code). Because that way we are no longer testing the actual code users will be using.

Let me know if I misunderstood something.

2023-03-13 07:03 UTC, shramee commented on scripts/devnet-run.sh
> +echo "Waiting for devnet... "
Aye, but that depends on the curl call failing. However with ports exposed it doesn't fail but just returns an empty response (which means that it's not live yet).
So added some code to continuously check until the response is not empty. And also logs number of try each second... (like a seconds counter)

2023-03-14 08:27 UTC, FabijanC commented on scripts/devnet-run.sh
> +echo "Waiting for devnet... "
Why is it bad that it depends on the curl call failing? Not failing gracefully? I think the curl command can also log the retries it's making.

2023-03-14 09:01 UTC, shramee commented on scripts/devnet-run.sh
> +echo "Waiting for devnet... "
Ohh we need the disgrace for it to keep re-trying, it should fail like the sky falling...
But it fails without an error with an empty response which is the problem...

2023-03-14 09:05 UTC, FabijanC commented on scripts/devnet-run.sh
> +echo "Waiting for devnet... "
And surely no flags/options can be passed to the command to fix it?

2023-03-15 08:46 UTC, shramee commented on scripts/devnet-run.sh
> +echo "Waiting for devnet... "
[Retry on any and all errors](https://everything.curl.dev/usingcurl/downloads/retry#retry-on-any-and-all-errors) sounds promising, but I quite like the stopwatch kinda thing. I think it improves the testing experience...
But let me know if we should see if retry on all errs works for us and replace with that.

2023-03-24 09:50 UTC, shramee commented
Hi Fabijan,
I think there might be another way to go about this. Without having to make any changes to the code itself. We should be able to use a lot of stuff from here.
I will update you in the first week in April, is that cool?

2023-03-28 13:20 UTC, FabijanC commented
> Hi Fabijan, I think there might be another way to go about this. Without having to make any changes to the code itself. We should be able to use a lot of stuff from here. I will update you in the first week in April, is that cool?

Hi Shramee, thanks for replying. That sounds good!

2023-04-28 11:30 UTC, shramee commented
Closed in favor of #343

2023-04-28 11:30 UTC, closed without merging