Cairo1 events
0xSpaceShard/starknet-hardhat-plugin pull request #380
Opened 2023-06-15 10:07 UTC by notV4l

Fix #378

2023-06-15 10:35 UTC, Nathan-SL commented
@notV4l your branch is still targeting `origin/plugin` of the example repo and that's why your tests are failing. I think you can change the target branch and repo to yours on`scripts/test-setup.sh`

2023-06-20 12:29 UTC, FabijanC requested changes

2023-06-20 14:29 UTC, notV4l commented on www/docs/dev.md
> +If you used `npm link` to link starknet-hardhat-plugin to starknet-hardhat-example, to run `declare-test` test case in `general-tests` test group from `starknet-hardhat-example` directory with :
i simplified/reworded it

2023-06-20 14:35 UTC, FabijanC approved these changes

2023-06-20 16:01 UTC, merged